# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d767b51a1fac612775a4290d9a0ce9aba23dd6e5593cbacc47f971026a546fe4103ca703eb5973e3503102597d818517e17b63ba8ecf21e841be985ceb5eaf

test:
  secret_key_base: 5efbfd18792aeaec91c1ea4b9128274aeb160246206f409eac4d0d1e0784e0db0e108af94380cbbd75f19a8abf68c30019d568a56e8330e42be886c651710182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
